pull_request_rules:
  - name: "Automatic merge when CI passes and approved (rebase by default)"
    conditions:
      - "#approved-reviews-by>=1"
      - "check-success=success"
      - "base=main"
      - "label=rebase"
      - -draft
      - -conflict
    actions:
      merge:
        method: rebase

  - name: "Automatic squash merge when CI passes and approved"
    conditions:
      - "#approved-reviews-by>=1"
      - "check-success=success"
      - "base=main"
      - "label=squash"
      - -draft
      - -conflict
    actions:
      merge:
        method: squash

  - name: "Delete head branch after merge but not if other PRs depend on it"
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false
